[[redirects]]
  from = "https://opensciencesoftware.com/*"
  to = "https://openscience.software/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://opensoftware.science/*"
  to = "https://openscience.software/:splat"
  status = 301
  force = true
